project:
  type: book

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

toc: true
toc-depth: 3
bibliography: references.bib
css: book.css

book:
  title: "Data Wrangling and Visualization in the Tidyverse"
  author:
  - John J. Curtin, PhD
  - Susan Wanta, MS
  site-url: https://github.io/jjcurtin/dwt
  repo-url: https://github.com/jjcurtin/dwt
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  chapters:
    - index.qmd
    - conflicts.qmd
    - cache.qmd
    - parallel_processing.qmd
    - file_and_path_management.qmd
    - exploring_dataframes.qmd
    - reproducible_examples.qmd
    - factors.qmd
    - recoding.qmd
    - iteration.qmd
    - functions.qmd
    - ggplot2.qmd
    - simulations.qmd
    - geolocation.qmd
    - programming.qmd
    - quarto.qmd
    - quarto.qmd
    - datetimes_dates.qmd
    - resources.qmd
